# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-detection-app
  template:
    metadata:
      labels:
        app: fraud-detection-app
    spec:
      containers:
      - name: fraud-detection-container
        image: asia-south1-docker.pkg.dev/vcc-group-28-project-g23ai2045/vcc-repo/fraud-detection-app:version-1
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "/fraud_detection/settings.py"  # Replace with your actual settings module
        - name: EXTERNAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP  # Dynamically gets the external IP
