# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
spec:
  type: LoadBalancer
  selector:
    app: fraud-detection-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
